### ISSUE TITLE
How to have a dropdown list?

### ISSUE THREAD

**Issue by emrys90** [alelievr/NodeGraphProcessor#129]
I read that Odin Serializer attributes aren't supported yet (and I'm on 2019.4 so can't use the newest stuff anyways once it's available), how would I go about having a dropdown list to choose from? My case is a dynamic list of strings that I would normally use the ValueDropdown attribute on

**Comment by alelievr** [comment]
Hello,

For such a case right now you have two choices: Create a node view and add the dropdown yourself with the UIElement API: https://docs.unity3d.com/ScriptReference/UIElements.PopupField_1.html.
There are examples of how to use it here: https://github.com/Unity-Technologies/UIElementsExamples.

Otherwise, you can create a custom field drawer using this attribute: https://github.com/alelievr/NodeGraphProcessor/blob/master/Assets/com.alelievr.NodeGraphProcessor/Runtime/Graph/Attributes.cs#L81 But I don't have any examples right now that uses it

**Comment by emrys90** [comment]
Thanks. The FieldDrawerAttribute seems to be along the lines of what I'm looking for, so I'll see if I can get it figured out on how to use it

**Comment by emrys90** [comment]
I couldn't figure out the drawer approach, wasn't working for me. I did get the custom node view approach working though. It's a bit tedious in comparison to just an attribute being applied, but it does work. Thanks!
