### ISSUE TITLE
How can we to implement the MonoBehaviour methods

### ISSUE THREAD

**Issue by weacw** [alelievr/NodeGraphProcessor#149]
## How can we to implement MonoBehaviour methods
https://docs.unity3d.com/ScriptReference/MonoBehaviour.html

**Comment by alelievr** [comment]
Hello, I'm not sure to understand the question, are you talking about the [GraphBehavior ](https://github.com/alelievr/NodeGraphProcessor/blob/master/Assets/Examples/GraphBehaviour.cs) class? or something else?

Otherwise, the graph has its own lifecycle so it's not possible to have all the message functions of MonoBehavior.

**Comment by weacw** [comment]
> Hello, I'm not sure to understand the question, are you talking about the [GraphBehavior ](https://github.com/alelievr/NodeGraphProcessor/blob/master/Assets/Examples/GraphBehaviour.cs) class? or something else?
> 
> Otherwise, the graph has its own lifecycle so it's not possible to have all the message functions of MonoBehavior.

Thank you for your reply.

I wanna implement  ` Flow Graphs` (`Start` `Update` `FixUpdate` and so on Unity Event Function in the graph)
Like [Bolt](https://assetstore.unity.com/packages/tools/visual-scripting/bolt-163802)

**Comment by alelievr** [comment]
Hum, I see. So I think the best way to do this would be to code a custom processor for the graph like this one: https://github.com/alelievr/NodeGraphProcessor/blob/master/Assets/Examples/ConditionalGraph/ConditionalProcessor.cs

That way, you can add an Update or FixedUpdate node that will trigger the execution of all connected nodes.

I guess since you want to use Start / Update functions you want your graph to be inside the scene? If that's the case, you can take this file as an example to implement a graph inside a component: https://github.com/alelievr/NodeGraphProcessor/blob/master/Assets/Examples/GraphBehaviour.cs

Then you can forward the Start / Update method of the Monobehaviour to your conditional graph processor like this:

```csharp
var processor = new ConditionalProcessor(graph);

void Update()
{
    processor .Update()
}
...
```
