### ISSUE TITLE
Support for [Range] attribute, or ability to easily support custom drawing attributes

### ISSUE THREAD

**Issue by arycama** [alelievr/NodeGraphProcessor#160]
It seems that to support built in attributes like this, I would need to override and re-implement most of the drawing logic in BaseNodeView.

It would be great if there is support for builtin attributes such as Range, Min, Max, etc.

Alternatively, if there's an easy way to make a custom attribute which allows us to override how it is drawn, that would be very useful.

**Comment by alelievr** [comment]
Hello, this is the same issue as #87. 
So same state: I'm making progress, but not there yet (still have the reload graph issue when a property is modified from a SerializedField inside a node)

**Comment by alelievr** [comment]
Support of all builtin unity attributes have been added with the latest master, they will be available in the next published package version (1.3.0)

Note that to use the range attribute, you'll need a fairly large node as the default inspector only shows the slider on fields with a certain min width:
![image](https://user-images.githubusercontent.com/6877923/124520943-3bca4a00-ddee-11eb-8574-358aed361acb.png)

Otherwise, you can remove the label of the field using `[InspectorName("")]` on the field like so:
![image](https://user-images.githubusercontent.com/6877923/124520975-556b9180-ddee-11eb-9dad-382ecfc42fa0.png)
