### ISSUE TITLE
Building the project

### ISSUE THREAD

**Issue by m3rt32** [alelievr/NodeGraphProcessor#22]
Hey there, when I try to build my projects with NodeGraphProcessor, I get lots of compile errors because some scripts are missing.

Is there a solution for this ?

I get errors like this:
`The type or namespace name 'UIElements' does not exist in the namespace 'UnityEditor' (are you missing an assembly reference?)
`

**Comment by alelievr** [comment]
Hi, Indeed it's my mistake, i did not separate the project in two asm def files for Editor and Runtime so unity tried to put editor scripts inside builds :(
I fixed this issue in this commit: https://github.com/alelievr/NodeGraphProcessor/commit/dd2ec017bbb1a997b1dc5c37f09d7c57f20b68e0

**Comment by m3rt32** [comment]
I'll check it out and report back to here. Thanks :)

**Comment by m3rt32** [comment]
I've managed to build the project but when I try to execute the graph on the build I got an error about serialization.

` A scripted object (probably Graph.Gameplay.GameplayGraph?) has a different serialization layout when loading. (Read 52 bytes but expected 2012 bytes)
08-21 18:14:36.477 25246 26636 E Unity   : Did you #ifdef UNITY_EDITOR a section of your serialized properties in any of your scripts?`

GameplayGraph is more or less like a custom graph just as the samples. But I believe something weird going on at serialization stuff. I am open to any suggestions.

Because when I try to execute my graph object with my RuntimeProcessor(a derived version of Processor base class) I got NullRefExceptions to access to node list.

**Comment by alelievr** [comment]
It's strange, i just tested with a simple graph and it works for me. Here is my graph: 
![image](https://user-images.githubusercontent.com/6877923/63471109-a11d2800-c46e-11e9-8a7f-9f144ce8bc76.png)
the asset is just a BaseGraph and i have this code that executes the graph at runtime:
```csharp
public class RuntimeGraph : MonoBehaviour
{
	public BaseGraph	graph;
	public ProcessGraphProcessor	processor;

	private void Start()
	{
		if (graph != null)
			processor = new ProcessGraphProcessor(graph);
	}

	int i = 0;

    void Update()
    {
		if (graph != null)
		{
			graph.SetParameterValue("Input", (float)i++);
			processor.Run();
			Debug.Log("Output: " + graph.GetParameterValue("Output"));
		}
    }
}
```
Do you have any additional fields serialized in your `GameplayGraph`  class that could cause this issue ? Since the error happens when the `ScriptableObject` is deserialized I'd say that it comes from a property inside the graph asset and not a node since they are serialized as json strings inside the graph `ScriptableObject`.
Btw i looked in the whole codebase and i don't see any `#if UNITY_EDITOR` that would imply this issue :/

**Comment by m3rt32** [comment]
I guess I have some properties, although, they are not quite serialized. GameplayGraph is just derived from a **CoreGraph** class and **Start Node** and **LoopNode** are the entry points. 
Start Node runs connected nodes to itself like step by step.
Loop Node runs every connection every frame just like Monobehaviour Update. My CoreGraph as follows.

`c#
  [System.Serializable]
    public class CoreGraph : BaseGraph
    {
        [NonSerialized]
        public StartNode startNode;

        [NonSerialized]
        public LoopNode loopNode;

        public CoreGraph()
        {
            base.onEnabled += Enabled;
        }

        private void Enabled()
        {
            // We should have only one OutputNode per graph
            startNode = nodes.FirstOrDefault(n => n is StartNode) as StartNode;
            loopNode = nodes.FirstOrDefault(n => n is LoopNode) as LoopNode;

            if (startNode == null)
                startNode = AddNode(BaseNode.CreateFromType<StartNode>(Vector2.zero)) as StartNode;

            if (loopNode == null)
                loopNode = AddNode(BaseNode.CreateFromType<LoopNode>(Vector2.zero - new Vector2(0f, -400f))) as LoopNode;
        }
    } `

**Comment by m3rt32** [comment]
I solved the issue. It was because of Graph classes stored in Editor folders and there was several things that I stored in Graph class as **Serializable.**

So issue is on my end not about the tool.

**Comment by alelievr** [comment]
Hum I wasn't aware of this behaviour but it seems logical that it was causing issues at deserialization. The problem is that i don't know if there is a way to prevent that or just having an error message when an editor class is serialized inside a runtime folder :/
Anyway, it's good thing that you found it :)

**Comment by m3rt32** [comment]
No problem! I am also thinking about making a little sample project for dialogue creation. 
Additionally I have a few ideas to add to system(graph generation for example,with unity script templates).
Lets  see how it goes!
