### ISSUE TITLE
Loop Node

### ISSUE THREAD

**Issue by cuddlecats** [alelievr/NodeGraphProcessor#27]
Hello!

Node Graph Processor is a wonderful framework, but I don't know how to make a loop node.
Can you help me?
Something like a [ForLoop node](https://docs.unrealengine.com/en-US/Engine/Blueprints/UserGuide/FlowControl/index.html) from the UE4.

**Comment by JasonOscar** [comment]
It took me some time to learn the project,Its nodes are modular，so you can learn its demo.I saw it five months ago. I kind of forgot.sorry,Hope this helps you.Fighting！
----- 原始邮件 -----
发件人：cuddlecats <notifications@github.com>
收件人：alelievr/NodeGraphProcessor <NodeGraphProcessor@noreply.github.com>
抄送人：Subscribed <subscribed@noreply.github.com>
主题：[alelievr/NodeGraphProcessor] Loop Node (#27)
日期：2019年10月08日 20点37分

Hello!
Node Graph Processor is a wonderful framework, but I don't know how to make a loop node.

Can you help me?

&mdash;

**Comment by alelievr** [comment]
Hello, sorry for the late answer. This can be implemented with a custom processor that inherits the `BaseGraphProcessor` class like in the ProcessGraphProcessor: https://github.com/alelievr/NodeGraphProcessor/blob/master/Assets/com.alelievr.NodeGraphProcessor/Runtime/Processing/ProcessGraphProcessor.cs.

Basically, you have two choices here:
- in the flow control nodes, you store the list of all nodes that are linked to the output and execute them based on loop, branch and other stuff. But if you do that, you need to remove all the nodes that depends from a flow control node of the processor list (because otherwise they will be executed like other nodes)
- Implement all the logic in the custom processor: search for control flow nodes and manage everything here, here you need the flow control data to be public from the nodes so they can be accessed in the processor.

At the end it really depends on either you want the control flow code to be scattered but cleaner or at the same place but relying on node data outside of the node.

I'll try to implement something in the examples if i can find some time to do it

**Comment by m3rt32** [comment]
Personally, I have created loop node and looping system similar to @alelievr 's first suggestion.

I can say it looks visually more compelling and artist friendly. I have been creating two entry points when graph is created such as loop and start. It works in a similar fashion to unitys implementation.

Though, I get connected nodes and run loop in a coroutine. You can use a loopnode.cs base class that inherits from node basenode.cs class. Then using reflection, you are able to filter and get only loop nodes that are connected to entry point.

**Comment by MMJM** [comment]
Does anyone have a loop node example?

**Comment by alelievr** [comment]
Hey, i began to make an implementation of a conditional graph execution following the second choise i listed above, it's currently in the [conditional](https://github.com/alelievr/NodeGraphProcessor/tree/conditional) branch. I just got a very simple first version with if nodes working:

![ConditionalGraph](https://user-images.githubusercontent.com/6877923/68548391-b90ca400-03ec-11ea-98cf-43e0f052d6b2.gif)

I'm trying to mimic the behaviour of unreal blueprints with the flow control (yellow square ports) but right now there is only the branch node that is working

**Comment by alelievr** [comment]
Hey, I just merged my branch with conditonal graph processing example in master:  https://github.com/alelievr/NodeGraphProcessor/commit/179f6cf15e76adbbf98f1a30a4bd7d04927afbfa
It contains a functional for loop implementation :) 
![ConditionalGraphForLoop](https://user-images.githubusercontent.com/6877923/69500269-e469b580-0ef9-11ea-9c4b-f58e793f7ecd.gif)
