### ISSUE TITLE
Have OutputAttribute allowMultiple = false

### ISSUE THREAD

**Issue by molocai** [alelievr/NodeGraphProcessor#3]
In the context of a flow graph I would like to prevent an output from being plugged into multiple inputs by using the OutputAttribute with a new parameter "allowMultiple" set to false (much like the InputAttribute).

I'd love to work on this feature if you point me in the right direction for it.

Thanks in advance

**Comment by alelievr** [comment]
Hi,

I think the simplest way to achieve this is to add a condition inside the connect callback to remove existing edges if the output port does not support multiple outputs (exactly like the default input behavior).
First thing you'll have add your parameter inside the `OutputAttribute` in [Attribute.cs](https://github.com/alelievr/NodeGraphProcessor/blob/master/Assets/NodeGraphProcessor/Runtime/Graph/Attributes.cs). Then [here in the BaseNode class](https://github.com/alelievr/NodeGraphProcessor/blob/master/Assets/NodeGraphProcessor/Runtime/Elements/BaseNode.cs#L116) instead of always setting isMultiple to false for outputnode, reference the value form the output node attribute. And finally add a condition (exactly like this on: [disconect edges block](https://github.com/alelievr/NodeGraphProcessor/blob/master/Assets/NodeGraphProcessor/Editor/Views/BaseGraphView.cs#L415)) but for output ports.
There maybe will have some other things that breaks because the code assumes that an output port always have `isMultiple` to false (which is counterintuitive) but i think it'll be okay.
Note that there is also another way to do that using the [graphview port capacity](https://github.com/alelievr/NodeGraphProcessor/blob/master/Assets/NodeGraphProcessor/Editor/Views/PortView.cs#L30) but i'm not really sure as i haven't tested how it behaves.

Let me know if you have any other questions :)

**Comment by molocai** [comment]
Thanks for the quick answer, I got it to work in a few minutes and so far everything seems to be working as intended ! :)

**Comment by alelievr** [comment]
Glad it worked :)
