### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Taenebron** [alelievr/NodeGraphProcessor#35]
Hey! I consider using this framework for some of my projects (like self-created Dialogue system). I already used xNode, but NodeGraphProcessor uses new APIs and I see fresh potential.

I'm not sure about some parts of documentation that are unclear for me:

1. "**Remaining to do:** Runtime processing without the editor" what does it mean in practice? What it affects? Is solution ready for implementation and optimized enough?

2. Licence: Would be nice to know for safety what licence project bases upon.

3. Node coloring: How I may tint nodes for readability? For now, examples are most important learning material - maybe I would find it out in some time. Would be perfect with some direct wiki clarifications related to features.

Thank you for developing this project! :)

**Comment by alelievr** [comment]
Hi, thanks for looking at this project :)

1. about the ```Remaining to do: Runtime processing without the editor``` I think it was never removed from the readme because i don't update it regularly. The graph processing is supposed to work in both the ediitor and player, at least last time i tested it was working. About performances i didn't checked at all but in runtime it shouldn't be that bad. In the editor since i'm using GraphView which is still in an experimental state (and misses LOD for nodes) you'll start to experience some lags when you have around ~250 nodes in you view and I don't know when the GraphView team will start to work on performance.

2. It's MIT license: you can check it here: https://github.com/alelievr/NodeGraphProcessor/blob/master/LICENSE

3. The style system i'm using is the [UIElement uss system](https://docs.unity3d.com/Manual/UIE-USS.html) you can have a custom style sheet per node by overriding the `layoutStyle` property like this: https://github.com/alelievr/NodeGraphProcessor/blob/master/Assets/Examples/DefaultNodes/Nodes/CustomPortsNode.cs#L20. In this example it will go fetch this styleSheet in the Resources folder: https://github.com/alelievr/NodeGraphProcessor/blob/master/Assets/Examples/Resources/TestType.uss which changes the color of the header.
Otherwise you can change it in script with the style property that is on every UIelement block: https://docs.unity3d.com/ScriptReference/UIElements.IStyle.html

I know there is a lot of documentation missing right now, i need to find the motivation and time to do it :)

**Comment by Taenebron** [comment]
Haha, documentation part is understandable. I see that I missed LICENSE file there.
Thanks alot! :)
