### ISSUE TITLE
Hello World Example and Contributions?

### ISSUE THREAD

**Issue by jeffcampbellmakesgames** [alelievr/NodeGraphProcessor#43]
Hi there, I am evaluating different open source node graph projects for Unity as the basis for other tools I'm writing, both internal and also open source. I like this one because the appearance matches the newer native Unity graph tools and that its available as a package (easy dependency management). I have a couple of questions for you when you have a chance:

* Do you have a hello world example available somewhere that would demonstrate how to setup a basic graph? I see you have several screenshots on the readme demonstrating the nodes/graphs, but other than the WIP project linked [here](https://github.com/alelievr/NodeGraphProcessor/issues/14) I'm not sure where to get started. I have followed some of the wiki instructions for creating nodes, graph views, but am not sure where to go from there.
* If I ended up using this I'd like to help contribute bug fixes/features as I can; how do you want contributions to be made, do you have any particular style guide for code, and is Trello the main backlog source for this project?

Thanks!

**Comment by alelievr** [comment]
Hey,

Indeed this project uses the new API for graph visualization in Unity: [GraphView](https://docs.unity3d.com/ScriptReference/Experimental.GraphView.GraphView.html) as well as some recent C# features :) 

> Do you have a hello world example available somewhere

All the screenshots from the readme are avaliable in this project ([Example folder](https://github.com/alelievr/NodeGraphProcessor/tree/master/Assets/Examples)), it also contains very simple implementation of graph like this one: https://github.com/alelievr/NodeGraphProcessor/tree/master/Assets/Examples/Editor/05_All which is a good starting point since it only have a toolbar and all basic graph functionality. As for asset management (open the graph when opening the asset), you can have a look at this file: https://github.com/alelievr/NodeGraphProcessor/blob/master/Assets/Examples/Editor/GraphAssetCallbacks.cs, it uses standard Unity API to open the graph window from the asset.  
Mixture is a much more advanced project without any documentation so I wouldn't recommend it as starting point, but if you already know the API / code it can provide some useful examples (I still need to write the readme though)

>If I ended up using this I'd like to help contribute bug fixes/features as I can

Every pull requests is welcomed :) I'll review them when i have some time to spend on the project.
I don't really enforces any coding convention, as long as the code is clean, commented and readable.  
And for trello, i think i'll move most of it to a Github project to make issue tracking and feature requests more visible and accessible.

**Comment by jeffcampbellmakesgames** [comment]
> Hey,
> 
> Indeed this project uses the new API for graph visualization in Unity: [GraphView](https://docs.unity3d.com/ScriptReference/Experimental.GraphView.GraphView.html) as well as some recent C# features :)
> 
> > Do you have a hello world example available somewhere
> 
> All the screenshots from the readme are avaliable in this project ([Example folder](https://github.com/alelievr/NodeGraphProcessor/tree/master/Assets/Examples)), it also contains very simple implementation of graph like this one: https://github.com/alelievr/NodeGraphProcessor/tree/master/Assets/Examples/Editor/05_All which is a good starting point since it only have a toolbar and all basic graph functionality. As for asset management (open the graph when opening the asset), you can have a look at this file: https://github.com/alelievr/NodeGraphProcessor/blob/master/Assets/Examples/Editor/GraphAssetCallbacks.cs, it uses standard Unity API to open the graph window from the asset.
> Mixture is a much more advanced project without any documentation so I wouldn't recommend it as starting point, but if you already know the API / code it can provide some useful examples (I still need to write the readme though)

Thanks for the heads up, I'll have to check that out. I've attempted to clone this repo and checkout the master branch, but strangely enough my GIT client has been crashing from what appears to be pulling the ShaderGraph submodule. 

![image](https://user-images.githubusercontent.com/1663648/75146958-7ef5b280-56fc-11ea-801c-16c4ec372940.png)

Is this submodule still needed? It appears that the code at that repo is no longer up-to-date and has moved to a separate repository.

![image](https://user-images.githubusercontent.com/1663648/75147028-ac426080-56fc-11ea-9a2a-94a53bb3f29b.png)

> > If I ended up using this I'd like to help contribute bug fixes/features as I can
> 
> Every pull requests is welcomed :) I'll review them when i have some time to spend on the project.
> I don't really enforces any coding convention, as long as the code is clean, commented and readable.
> And for trello, i think i'll move most of it to a Github project to make issue tracking and feature requests more visible and accessible.

Sounds great, looking forward to it! 👍

**Comment by alelievr** [comment]
> Is this submodule still needed? It appears that the code at that repo is no longer up-to-date and has moved to a separate repository.

I didn't see that there was still the old git submodule in this repo it's not used anymore. I just deleted it in 5889bc95f5659dd8d6a1ccf15e51183ab73e2031, thanks :)
