### ISSUE TITLE
Black window

### ISSUE THREAD

**Issue by Snowirbix** [alelievr/NodeGraphProcessor#44]
I imported the package, and added the example folder in my assets to test.
When I open an asset like "Basic example", it works great.
But when I go in the window menu and click on 01_DefaultGraph or any other graphs, it just open a black editor window.
I opened the UIElements Debugger and there is only the graphRootView with no children visualElements.

**Comment by qtghost** [comment]
> I imported the package, and added the example folder in my assets to test.
> When I open an asset like "Basic example", it works great.
> But when I go in the window menu and click on 01_DefaultGraph or any other graphs, it just open a black editor window.
> I opened the UIElements Debugger and there is only the graphRootView with no children visualElements.

unity version?

**Comment by alelievr** [comment]
Hey,

I guess it's because there is no graph asset associated with the graph window when you open it like that.

I fixed this issue in f5c2dbbed2916005f4a43f4a5fc3ef5ada733454, you should be able to edit the graph like before and the data will be stored in a temporary graph (it means that you'll loose your graph when closing the project).  
![NodeGraphExample](https://user-images.githubusercontent.com/6877923/77234497-37edc680-6baf-11ea-9ff4-aa1a11117b63.gif)

Note that you can also double click on a graph asset in the project view to open a graph asset (which is saved on the disk so you'll not loose your data when closing the editor).
