### ISSUE TITLE
NodePort as Proxy

### ISSUE THREAD

**Issue by Mefodei** [alelievr/NodeGraphProcessor#45]
Hello there.
I'm trying to use your graph as View for my own graph data structure.
And i'm stuck on NodePort API usage.
For the reason that i have my own memory Object, i need option specify Owner and FieldInfo as External source of NodePort

```csharp
public NodePort(BaseNode owner, string fieldName, PortData portData)
		{
			this.fieldName = fieldName;
			this.owner = owner;
			this.portData = portData;

			fieldInfo = owner.GetType().GetField(fieldName, BindingFlags.Public |                                                      BindingFlags.NonPublic | BindingFlags.Instance);

```
If it possible  Port Source data should be wrap as your PortData for use it like abstraction

**Comment by alelievr** [comment]
Hey,

Would add a new constructor that takes directly a FieldInfo in parameter help in your case ? If it works for you I can add it to the API.
Also I don't know if it's relevant in your case but you could also emulate your nodes through mine using the custom port API: https://github.com/alelievr/NodeGraphProcessor/blob/master/Assets/Examples/DefaultNodes/Nodes/CustomPortDataNode.cs#L37. It allows you to generate any number of ports different name / types from a single property.

That being said if you only want to visualize your graph data structure and not interact with it (no manipulation like edge connection, creating new nodes, etc.) it may be easier to do with the Unity GraphView API since it only handles the visualization part: https://docs.unity3d.com/ScriptReference/Experimental.GraphView.GraphView.html

**Comment by Mefodei** [comment]
Hello 
You are correct. It would be nice if you add API 
like that into **NodePort**:
```csharp
/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="owner">owner node</param>
		/// <param name="fieldName">the C# property name</param>
		/// <param name="portData">Data of the port</param>
		public NodePort(BaseNode owner, string fieldName, PortData portData) :
			this(owner, owner, fieldName, portData)
		{
			
		}

		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="owner">owner node</param>
		/// <param name="fieldOwner"></param>
		/// <param name="fieldName">the C# property name</param>
		/// <param name="portData">Data of the port</param>
		public NodePort(BaseNode owner,object fieldOwner, string fieldName, PortData portData)
		{
			this.fieldName = fieldName;
			this.owner     = owner;
			this.portData  = portData;
			this.valueOwner = fieldOwner;

			fieldInfo = valueOwner.GetType().GetField(
				fieldName,
				BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
			customPortIOMethod = CustomPortIO.GetCustomPortMethod(owner.GetType(), fieldName);
		}
```

And i notice your are use direct FieldInfo.Get/Set Value call. I think it would be nice to move it into separate method of port api to future extend-ability and SRP(hope that's helpful)

About my usage of your tools. Right now i use self-refactored version of XNode graph for Unity for implement Full Reactive Graph system.
https://github.com/UniGameTeam/UniGame.GameFlow

And so I need support base operations like: create, remove, connect etc. But your version fully based on Scriptable Object as a Data container. 
If you can add separate inheritance hierarchy tree for support MonoBehaviour/Prefabs Data Container for scene asset reference, then i can use your tool directly without Adapter between two systems

Thx for advice about multiport support.

**Comment by alelievr** [comment]
Hey, sorry for the delay. I added a new constructor in the NodePort class based on what you posted: 931fb7ec920668745b844d9352d5b98e36bd68f0.

I also patched the calls to Get/SetValue with the good field owner so tell me if it works for you :)

**Comment by Mefodei** [comment]
Thank you. That's very helpful for me
