### ISSUE TITLE
Negative Compute Order

### ISSUE THREAD

**Issue by GangstaHikka** [alelievr/NodeGraphProcessor#58]
The computing order becomes negative on a large graph.
UPD: Replacing int to long on the "compute order" field solved the problem, but I don't think that for a long time. 
Maybe implement another order computing algorithm? 

![Proof1](https://user-images.githubusercontent.com/40768760/86120477-0dc87080-badd-11ea-8e69-0bdea3ca1fd4.png)
![Proof2](https://user-images.githubusercontent.com/40768760/86120507-19b43280-badd-11ea-94bc-27403dd58c81.png)

**Comment by alelievr** [comment]
Hello, the current algorithm used to compute the order is a BFS, incrementing the compute order for each compute dependecy starting from 0.
I think the way your graph was made highlight an issue with the current system, because it adds the compute order of the dependencies when you have a lot of edges as input to one node it rapidly grows.

I already planned to change the compute order of the graph to a DFS instead (for processing graph with multiple parts) that may solve your issue, I'll update the issue when I have some news

**Comment by alelievr** [comment]
So I changed the compute order in this commit: https://github.com/alelievr/NodeGraphProcessor/commit/c712b2861755da6489f258ae03253aa8c7dc4389, note that the new algorithm is this one: https://en.wikipedia.org/wiki/Depth-first_search
I tried with a large graph and it indeed fixed the negative compute order issue. 

If you encounter problems with the new algorithm, please let me know. Also you can revert to the old algorithm by changing
```CSharp
		public void UpdateComputeOrder(ComputeOrderType type = ComputeOrderType.DepthFirst)
```
to
```CSharp
		public void UpdateComputeOrder(ComputeOrderType type = ComputeOrderType.BreadthFirst)
```
