### ISSUE TITLE
Process/Traverse the graph

### ISSUE THREAD

**Issue by mlflabs** [alelievr/NodeGraphProcessor#61]
First of all, super excited about this project, i already made some simple nodes in just a few mins.

Not a bug but an example request.

Could you show us how to process the made graph, load it, run it, jump into some non-starter nodes.
A very simple example would be just great

Mike

**Comment by alelievr** [comment]
Hello,

First, loading the graph can be made using standard unity loading functions such as [Resources.Load](https://docs.unity3d.com/ScriptReference/Resources.Load.html), you'll then have access to the graph API to set external parameter or change some settings in your graph.

Then to be able to run the graph, you need a Processor. By default all the graphs uses this simple processor: [ProcessGraphProcessor.cs](https://github.com/alelievr/NodeGraphProcessor/blob/master/Assets/com.alelievr.NodeGraphProcessor/Runtime/Processing/ProcessGraphProcessor.cs) it only supports traversing all the nodes in the graph and executing them. But there is an API to create your own processor: https://alelievr.github.io/NodeGraphProcessor/api/GraphProcessor.BaseGraphProcessor.html.

Here's a simple example of how the processor is used to process the graph: 
https://github.com/alelievr/NodeGraphProcessor/blob/master/Assets/Scenes/RuntimeGraph.cs


There is a second graph processing algorithm in this repo which executes nodes conditionally (following a flow of conditional nodes like unreal blueprint system), here's the source file:
https://github.com/alelievr/NodeGraphProcessor/blob/master/Assets/Examples/ConditionalGraph/ConditionalProcessor.cs

As you can see the code is more complicated because there are several cases to handle branching and loops, I suppose you can take this as example to "jump" into the execution of some nodes.
