### ISSUE TITLE
ComputeOrderType.DepthFirst performance dramatically degradation. 

### ISSUE THREAD

**Issue by GangstaHikka** [alelievr/NodeGraphProcessor#78]
The performance of add and remove node actions begins to degrade significantly on the high count of nodes.
The root of the issue is a DFS algorithm. 
BFS works without any performance issues at all. 

Here green is an ok performance point and red is a point where issues start.
![изображение](https://user-images.githubusercontent.com/40768760/89788414-cbf10800-db27-11ea-8268-29edc5a5f4ae.png)

All graph
![изображение](https://user-images.githubusercontent.com/40768760/89788583-12466700-db28-11ea-851b-c9db411d6978.png)

**Comment by alelievr** [comment]
Hello, thanks for reporting this issue, I'll try to fix it asap

**Comment by alelievr** [comment]
The fix is available here: https://github.com/alelievr/NodeGraphProcessor/commit/6630f1fd07722966c94b01721bbeb1e5b4c0629b (master)
![BigGraph](https://user-images.githubusercontent.com/6877923/89889894-b84eab80-dbd2-11ea-84fa-5fc838436de7.gif)

As you can see the compute order is now much cleaner and should not cause any performance issues with a this kind of graph layout.

**Comment by GangstaHikka** [comment]
Yep, works wonderful, thank you for excellent support!
