### ISSUE TITLE
ScriptableObject reference on node possible? (null in build)

### ISSUE THREAD

**Issue by jejelite** [alelievr/NodeGraphProcessor#81]
Is it's possible to serialize scriptableObject reference? Everything is working in editor but in a build the variable "AiAction" is null when the node is evaluated.
```
[System.Serializable, NodeMenuItem("Obsolete/AiAction")]
public class AIActionNode : LeafNode
{
    [SerializeField] private AIAction action = null;

    [Input(name = "AIMaster", allowMultiple = false)]
    public AIMaster aiMaster;

    protected override NodeState OnEvaluate()
    {
        return aiMaster.DoAction(action);
    }
}

```
![image](https://user-images.githubusercontent.com/20047579/90824053-c902ce00-e304-11ea-8d71-5379975d3746.png)

**Comment by alelievr** [comment]
Hello, from what I looked it's a limitation of the JSON serialization system implemented in Unity. 

Fortunately, I plan to refactor the serialization system with [SerializeReference] instead of JSON to fix a bunch of issues like this one but I need to wait for [this issue](https://issuetracker.unity3d.com/issues/serializereference-non-serialized-initialized-fields-lose-their-values-when-entering-play-mode) to be backported in 2019.4 before landing the changes (it should happen within a couples of weeks).
I'll update this issue when the refactor lands.

**Comment by jejelite** [comment]
All good keep the good work , for people having the same problem a good work around is replacing the input by a string representing a id of the ScriptableObject inside a dictionnary<String, YourScriptableObject> on a Monobehavior.
