### ISSUE TITLE
Inspector window not showing custom properties

### ISSUE THREAD

**Issue by mlflabs** [alelievr/NodeGraphProcessor#95]
Hello

I have some parameters exposed, now if if its a string, vector3 or gameobject, it all shows up in the inspector properties.

But if I make a struct, or a custom class, even if they are serializable, they don't show up.  Is there a way to show these?

Mike

**Comment by alelievr** [comment]
Hey, 

this is because I'm building directly VisualElement fields using a FieldFactory class, that can only handle a few types listed here: https://github.com/alelievr/NodeGraphProcessor/blob/master/Assets/com.alelievr.NodeGraphProcessor/Editor/Utils/FieldFactory.cs#L32

You can still create a custom editor with the [FieldDrawer] attribute, you just need to create a class that inherit from VisualElement and implements INotifyValueChanged<T>, then the rest should be handled by the FieldFactory.

Note that this issue would be solved by using PropertyFields instead of manually creating all those VisualElements but it's not possible currently because the value of the parameter is serialized as json which is not compatible with PropertyFields. I plan to use [SerializeReference] to fix this but there no ETA for it.

**Comment by mlflabs** [comment]
Thanks for the reply, for now ill stick to the basic properties, its good enough. Keep up the great work.
